In [17]:
! pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [18]:
import numpy as np

# 🧮 NumPy - Quick Revision

## ✅ What is NumPy?

- **NumPy** is a **Python library** used for **working with arrays**.
- It supports:
  - **Linear Algebra**
  - **Fourier Transform**
  - **Matrix Operations**
- **Created by:** Travis Oliphant in **2005**
- **Open Source** and free to use.
- **Full Form:** **Numerical Python**

---

## 🚀 Why Use NumPy?

### 📌 Speed Advantage Over Lists
- NumPy arrays are stored in **one continuous block of memory**.
- Enables **faster processing** due to:
  - **Locality of Reference** (better CPU cache utilization)
  - **Vectorized operations** (no need for Python loops)

> 🆚 Traditional Python lists are slower because each element can be stored in different memory locations.

---

## ⚙️ Language Used

- Written **partially in Python**
- **Core parts (performance-critical)** written in **C and C++**
- Combines Python's ease of use with C/C++ speed

---

## 🔢 ndarray - NumPy Array Object

- NumPy provides a high-performance multidimensional array object: `ndarray`
- Offers **many built-in functions** to operate on arrays efficiently

---

## 📊 Why is NumPy Essential in Data Science?

- Arrays are fundamental in:
  - **Data Analysis**
  - **Machine Learning**
  - **Scientific Computing**
- NumPy's efficiency makes it ideal where **performance and memory** are crucial

---

## 💡 Summary

| Feature                | Details                                |
|------------------------|----------------------------------------|
| Library Name           | NumPy                                  |
| Purpose                | Fast array and matrix computation      |
| Written In             | Python (interface), C/C++ (core)       |
| Array Type             | `ndarray`                              |
| Performance            | ~50x faster than Python lists          |
| Applications           | Data science, ML, scientific computing |

---


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(np.__version__)
arr_1 = np.array((1, 2, 3, 4, 5))
arr_2 = np.array([1, 2, 3, 4, 5])
arr_3 = np.array({1, 2, 3, 4, 5})
print(arr)
print(type(arr))

print(arr_1)
print(type(arr_1))

print(arr_2)
print(type(arr_2))

print(arr_3)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>
2.2.6
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


# 🧱 Creating a NumPy `ndarray` Object

## 📌 What is an `ndarray`?

- In **NumPy**, the core data structure is called an **`ndarray` (n-dimensional array)**.
- It allows **fast, efficient operations** on large collections of numerical data.

---

## 🛠️ How to Create an `ndarray`?

### ✅ Using `array()` function:

You can pass:

A list

A tuple

Any array-like object

Even though a set uses curly braces {}, it still gets converted to an ndarray.

Important: Sets are unordered, so the order of elements in the resulting array may not match the input.




# 🧮 Dimensions in NumPy Arrays

## 📌 What is a Dimension?

A **dimension** in NumPy refers to the **level of depth** in an array, or how many levels of nesting exist.

Think of dimensions as:
- 1D → Single row (flat)
- 2D → Rows and columns (matrix)
- 3D → Multiple 2D arrays (stacked)

---

## 🔢 NumPy Array Dimensions Examples

### ✅ 0-D Arrays (Scalar)
```python
import numpy as np
a = np.array(42)
print(a.ndim)  # Output: 0


| Dimension | Description              | Example Shape      | Example Value                               |
|-----------|--------------------------|---------------------|----------------------------------------------|
| 0-D       | Scalar (single value)     | `()`               | `np.array(42)`                               |
| 1-D       | Vector (1 axis)           | `(3,)`             | `np.array([1, 2, 3])`                         |
| 2-D       | Matrix (rows & columns)   | `(2, 3)`           | `np.array([[1, 2, 3], [4, 5, 6]])`            |
| 3-D       | Tensor (stack of matrices)| `(2, 2, 3)`        | `np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])` |
| n-D       | Higher-dim arrays         | `(dim1, dim2, ...)`| `np.array(..., ndmin=n)`                     |
